version: "3.8"

services:
  you2rss-server:
    # The image tag will be replaced by the GitHub Actions workflow
    image: ghcr.io/korjavin/you2rss:latest
    container_name: you2rss-server
    command: ./server
    networks:
      - traefik-network
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      REDIS_ADDR: "${REDIS_ADDR}"
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      AUDIO_STORAGE_PATH: "/app/audio"
      BASE_URL: "${BASE_URL}"
    volumes:
      - audio_data:/app/audio
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.you2rss.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.you2rss.entrypoints=websecure"
      - "traefik.http.routers.you2rss.tls.certresolver=myresolver"
      - "traefik.http.services.you2rss.loadbalancer.server.port=8080"
    restart: unless-stopped

  you2rss-worker:
    # The image tag will be replaced by the GitHub Actions workflow
    image: ghcr.io/korjavin/you2rss:latest
    container_name: you2rss-worker
    command: ./worker
    networks:
      - traefik-network
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      REDIS_ADDR: "${REDIS_ADDR}"
      AUDIO_STORAGE_PATH: "/app/audio"
    volumes:
      - audio_data:/app/audio
    restart: unless-stopped

  you2rss-scheduler:
    # The image tag will be replaced by the GitHub Actions workflow
    image: ghcr.io/korjavin/you2rss:latest
    container_name: you2rss-scheduler
    command: ./scheduler
    networks:
      - traefik-network
    environment:
      REDIS_ADDR: "${REDIS_ADDR}"
    restart: unless-stopped

volumes:
  audio_data:

networks:
  traefik-network:
    external: true