version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: yt_podcaster
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

  server:
    build: .
    command: ./server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: "postgres://user:password@postgres:5432/yt_podcaster?sslmode=disable"
      REDIS_ADDR: "redis:6379"
      TELEGRAM_BOT_TOKEN: ${TELEGRAM_BOT_TOKEN}
      AUDIO_STORAGE_PATH: "/app/audio"
      BASE_URL: "http://localhost:8080"
    volumes:
      - audio_data:/app/audio

  worker:
    build: .
    command: ./worker
    depends_on:
      - postgres
      - redis
    environment:
      DATABASE_URL: "postgres://user:password@postgres:5432/yt_podcaster?sslmode=disable"
      REDIS_ADDR: "redis:6379"
      AUDIO_STORAGE_PATH: "/app/audio"
    volumes:
      - audio_data:/app/audio

  scheduler:
    build: .
    command: ./scheduler
    depends_on:
      - redis
    environment:
      REDIS_ADDR: "redis:6379"

volumes:
  postgres_data:
  audio_data:
