version: "3.8"

services:
  you2rss-postgres:
    image: postgres:13-alpine
    container_name: you2rss-postgres
    environment:
      POSTGRES_USER: you2rss
      POSTGRES_PASSWORD: you2rss_password
      POSTGRES_DB: yt_podcaster
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - you2rss-internal
      - traefik-network
    restart: unless-stopped

  you2rss-redis:
    image: redis:6-alpine
    container_name: you2rss-redis
    networks:
      - you2rss-internal
      - traefik-network
    restart: unless-stopped

  you2rss-migrate:
    # The image tag will be replaced by the GitHub Actions workflow
    image: ghcr.io/korjavin/you2rss:b869a2d75424ab456be2aac447ce0b89f659ba46
    container_name: you2rss-migrate
    depends_on:
      - you2rss-postgres
    networks:
      - you2rss-internal
    environment:
      DATABASE_URL: "postgres://you2rss:you2rss_password@you2rss-postgres:5432/yt_podcaster?sslmode=disable"
    command: >
      sh -c "
        apk add --no-cache postgresql-client &&
        until pg_isready -h you2rss-postgres -p 5432 -U you2rss; do
          echo 'Waiting for postgres...'
          sleep 2
        done &&
        for file in /app/migrations/*.up.sql; do
          echo \"Running migration: $$file\"
          psql $$DATABASE_URL -f \"$$file\"
        done &&
        echo 'Migrations completed'
      "
    restart: "no"

  you2rss-server:
    # The image tag will be replaced by the GitHub Actions workflow
    image: ghcr.io/korjavin/you2rss:b869a2d75424ab456be2aac447ce0b89f659ba46
    container_name: you2rss-server
    command: ./server
    depends_on:
      - you2rss-postgres
      - you2rss-redis
      - you2rss-migrate
    networks:
      - you2rss-internal
      - traefik-network
    environment:
      DATABASE_URL: "postgres://you2rss:you2rss_password@you2rss-postgres:5432/yt_podcaster?sslmode=disable"
      REDIS_ADDR: "you2rss-redis:6379"
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN}"
      AUDIO_STORAGE_PATH: "/app/audio"
      BASE_URL: "${BASE_URL}"
      # Optional settings with sensible defaults
      PORT: "8080"
      RATE_LIMIT_PER_MINUTE: "100"
      RATE_LIMIT_BURST: "5"
      MAX_SUBSCRIPTIONS_PER_USER: "100"
      PROCESS_VIDEO_TIMEOUT_MINUTES: "15"
      CHANNEL_INFO_TIMEOUT_SECONDS: "15"
      CHECK_CHANNEL_TIMEOUT_MINUTES: "2"
    volumes:
      - audio_data:/app/audio
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.you2rss.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.you2rss.entrypoints=websecure"
      - "traefik.http.routers.you2rss.tls.certresolver=myresolver"
      - "traefik.http.services.you2rss.loadbalancer.server.port=8080"
    restart: unless-stopped

  you2rss-worker:
    # The image tag will be replaced by the GitHub Actions workflow
    image: ghcr.io/korjavin/you2rss:b869a2d75424ab456be2aac447ce0b89f659ba46
    container_name: you2rss-worker
    command: ./worker
    depends_on:
      - you2rss-postgres
      - you2rss-redis
      - you2rss-migrate
    networks:
      - you2rss-internal
    environment:
      DATABASE_URL: "postgres://you2rss:you2rss_password@you2rss-postgres:5432/yt_podcaster?sslmode=disable"
      REDIS_ADDR: "you2rss-redis:6379"
      AUDIO_STORAGE_PATH: "/app/audio"
      # Optional settings with sensible defaults
      PROCESS_VIDEO_TIMEOUT_MINUTES: "15"
      CHECK_CHANNEL_TIMEOUT_MINUTES: "2"
    volumes:
      - audio_data:/app/audio
    restart: unless-stopped

  you2rss-scheduler:
    # The image tag will be replaced by the GitHub Actions workflow
    image: ghcr.io/korjavin/you2rss:b869a2d75424ab456be2aac447ce0b89f659ba46
    container_name: you2rss-scheduler
    command: ./scheduler
    depends_on:
      - you2rss-redis
    networks:
      - you2rss-internal
    environment:
      REDIS_ADDR: "you2rss-redis:6379"
    restart: unless-stopped
volumes:
  audio_data:
  postgres_data:

networks:
  you2rss-internal:
  traefik-network:
    name: ${NETWORK_NAME:-traefik-network}
    external: ${NETWORK_EXTERNAL:-true}
